var N = null;var sourcesIndex = {};
sourcesIndex["bitflags"] = {"name":"","files":["lib.rs"]};
sourcesIndex["byteorder"] = {"name":"","files":["io.rs","lib.rs"]};
sourcesIndex["cfg_if"] = {"name":"","files":["lib.rs"]};
sourcesIndex["derivative"] = {"name":"","files":["ast.rs","attr.rs","bound.rs","clone.rs","cmp.rs","debug.rs","default.rs","hash.rs","lib.rs","matcher.rs","paths.rs","utils.rs"]};
sourcesIndex["enumflags2"] = {"name":"","files":["fallible.rs","formatting.rs","lib.rs"]};
sourcesIndex["enumflags2_derive"] = {"name":"","files":["lib.rs"]};
sourcesIndex["fastrand"] = {"name":"","files":["lib.rs"]};
sourcesIndex["libc"] = {"name":"","dirs":[{"name":"unix","dirs":[{"name":"linux_like","dirs":[{"name":"linux","dirs":[{"name":"gnu","dirs":[{"name":"b64","dirs":[{"name":"x86_64","files":["align.rs","mod.rs","not_x32.rs"]}],"files":["mod.rs"]}],"files":["align.rs","mod.rs"]}],"files":["align.rs","mod.rs"]}],"files":["mod.rs"]}],"files":["align.rs","mod.rs"]}],"files":["fixed_width_ints.rs","lib.rs","macros.rs"]};
sourcesIndex["libportal"] = {"name":"","dirs":[{"name":"desktop","files":["account.rs","background.rs","camera.rs","device.rs","email.rs","file_chooser.rs","game_mode.rs","inhibit.rs","location.rs","memory_monitor.rs","mod.rs","network_monitor.rs","notification.rs","open_uri.rs","print.rs","remote_desktop.rs","screencast.rs","screenshot.rs","secret.rs","settings.rs","trash.rs","wallpaper.rs"]},{"name":"documents","files":["document.rs","file_transfer.rs","mod.rs"]},{"name":"flatpak","files":["mod.rs","update_monitor.rs"]}],"files":["lib.rs","request.rs","session.rs","window_identifier.rs"]};
sourcesIndex["nix"] = {"name":"","dirs":[{"name":"net","files":["if_.rs","mod.rs"]},{"name":"sys","dirs":[{"name":"ioctl","files":["linux.rs","mod.rs"]},{"name":"ptrace","files":["linux.rs","mod.rs"]},{"name":"socket","files":["addr.rs","mod.rs","sockopt.rs"]}],"files":["aio.rs","epoll.rs","eventfd.rs","inotify.rs","memfd.rs","mman.rs","mod.rs","pthread.rs","quota.rs","reboot.rs","select.rs","sendfile.rs","signal.rs","signalfd.rs","stat.rs","statfs.rs","statvfs.rs","sysinfo.rs","termios.rs","time.rs","uio.rs","utsname.rs","wait.rs"]}],"files":["dir.rs","errno.rs","fcntl.rs","features.rs","ifaddrs.rs","kmod.rs","lib.rs","macros.rs","mount.rs","mqueue.rs","poll.rs","pty.rs","sched.rs","ucontext.rs","unistd.rs"]};
sourcesIndex["once_cell"] = {"name":"","files":["imp_std.rs","lib.rs"]};
sourcesIndex["proc_macro2"] = {"name":"","files":["detection.rs","fallback.rs","lib.rs","parse.rs","wrapper.rs"]};
sourcesIndex["proc_macro_crate"] = {"name":"","files":["lib.rs"]};
sourcesIndex["quote"] = {"name":"","files":["ext.rs","format.rs","ident_fragment.rs","lib.rs","runtime.rs","spanned.rs","to_tokens.rs"]};
sourcesIndex["scoped_tls"] = {"name":"","files":["lib.rs"]};
sourcesIndex["serde"] = {"name":"","dirs":[{"name":"de","files":["from_primitive.rs","ignored_any.rs","impls.rs","mod.rs","utf8.rs","value.rs"]},{"name":"private","files":["de.rs","macros.rs","mod.rs","ser.rs"]},{"name":"ser","files":["fmt.rs","impls.rs","impossible.rs","mod.rs"]}],"files":["export.rs","integer128.rs","lib.rs","macros.rs"]};
sourcesIndex["serde_derive"] = {"name":"","dirs":[{"name":"internals","files":["ast.rs","attr.rs","case.rs","check.rs","ctxt.rs","mod.rs","symbol.rs"]}],"files":["bound.rs","de.rs","dummy.rs","fragment.rs","lib.rs","pretend.rs","ser.rs","try.rs"]};
sourcesIndex["serde_repr"] = {"name":"","files":["lib.rs","parse.rs"]};
sourcesIndex["syn"] = {"name":"","dirs":[{"name":"gen","files":["clone.rs","debug.rs","eq.rs","gen_helper.rs","hash.rs","visit.rs"]}],"files":["attr.rs","bigint.rs","buffer.rs","custom_keyword.rs","custom_punctuation.rs","data.rs","derive.rs","discouraged.rs","error.rs","export.rs","expr.rs","ext.rs","file.rs","generics.rs","group.rs","ident.rs","item.rs","lib.rs","lifetime.rs","lit.rs","lookahead.rs","mac.rs","macros.rs","op.rs","parse.rs","parse_macro_input.rs","parse_quote.rs","pat.rs","path.rs","print.rs","punctuated.rs","reserved.rs","sealed.rs","span.rs","spanned.rs","stmt.rs","thread.rs","token.rs","tt.rs","ty.rs","verbatim.rs","whitespace.rs"]};
sourcesIndex["toml"] = {"name":"","files":["datetime.rs","de.rs","lib.rs","macros.rs","map.rs","ser.rs","spanned.rs","tokens.rs","value.rs"]};
sourcesIndex["unicode_xid"] = {"name":"","files":["lib.rs","tables.rs"]};
sourcesIndex["void"] = {"name":"","files":["lib.rs"]};
sourcesIndex["zbus"] = {"name":"","files":["address.rs","connection.rs","error.rs","fdo.rs","guid.rs","lib.rs","message.rs","message_field.rs","message_fields.rs","message_header.rs","object_server.rs","owned_fd.rs","proxy.rs","utils.rs"]};
sourcesIndex["zbus_macros"] = {"name":"","files":["error.rs","iface.rs","lib.rs","proxy.rs","utils.rs"]};
sourcesIndex["zvariant"] = {"name":"","files":["array.rs","basic.rs","de.rs","dict.rs","encoding_context.rs","error.rs","fd.rs","from_value.rs","into_value.rs","lib.rs","object_path.rs","owned_value.rs","ser.rs","signature.rs","signature_parser.rs","str.rs","structure.rs","type.rs","utils.rs","value.rs"]};
sourcesIndex["zvariant_derive"] = {"name":"","files":["dict.rs","lib.rs","type.rs","utils.rs"]};
createSourceSidebar();
